# Generated by Django 5.1.6 on 2025-03-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.IntegerField(default=0),
        ),
    ]
