# Generated by Django 5.1.6 on 2025-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_urgency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(default='low', max_length=100),
        ),
    ]
