# Generated by Django 5.2 on 2025-04-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
