# Generated by Django 5.2 on 2025-05-05 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_uploadedimage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.uploadedimage'),
        ),
    ]
